name = "gripe"
version = "0.0.1"
description = "Stripe API bindings for Gleam."

licences = ["MIT"]
repository = { type = "github", user = "raquentin", repo = "gripe" }

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.2.4 and < 1.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"

[erlang]
otp_release = "24"
